#!/usr/bin/env node
/**
 * gen-version.mjs — write src/version.ts from package.json's version field so the
 * SDK's User-Agent stays in lockstep with the published version without a manual
 * edit. Wired as the `prebuild` npm hook (runs before every `tsc`).
 *
 *   node scripts/gen-version.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, "..");

const pkg = JSON.parse(readFileSync(path.join(root, "package.json"), "utf8"));
const version = pkg.version;
if (!version || typeof version !== "string") {
  console.error("gen-version: package.json has no valid version field");
  process.exit(1);
}

const out = `// AUTO-GENERATED by scripts/gen-version.mjs — do not edit by hand.
// Regenerated from package.json on every \`npm run build\` (prebuild hook).
export const VERSION = ${JSON.stringify(version)};
`;

const target = path.join(root, "src", "version.ts");
writeFileSync(target, out);
console.log(`gen-version: wrote src/version.ts (VERSION = ${version})`);
